### ISSUE TITLE
jQuery is not defined

### ISSUE THREAD

**Issue by ValBerthe** [jondot/react-flight#11]
Hey ! Wanted to mention that the project seems really cool. However, I ran into this error while trying to use Flight and therefore I cannot test it myself.

**Steps to reproduce:**

On an existing project, run:

`npm i react-flight --save`

Install jQuery/Zepto (one of them):

`npm i zepto --save`

`npm i jquery --save`

Import it in js file:

`import Flight, {Frame} from 'react-flight/dom';`

Use the doc's example, and got : 

![capture d ecran 2017-06-22 a 15 02 20 2](https://user-images.githubusercontent.com/17201868/27435463-9b8ba99c-575c-11e7-9846-cbcbad56380c.png)

**Comment by jondot** [comment]
Should be fixed now. Can you git pull and try again?

**Comment by ValBerthe** [comment]
Still no luck :(

**Comment by jondot** [comment]
Ah, sorry I didn't notice you were not starting from the example.

So the idea is that you should have jQuery available for the dependencies in `react-flight`. Currently  `tweene-velocity` requires it in such a way and we have to comply.

If you want to add jQuery via webpack, you need to configure webpack (which requires eject). If you want the shortest way without ejecting, add jQuery to your `public/index.html` as in here: https://github.com/jondot/react-flight/blob/master/examples/compos/public/index.html#L47

**Comment by ValBerthe** [comment]
@jondot Thanks, it did the trick !

**Comment by DevManny** [comment]
I want this to work without jQuery 😭  

What are you using `tweene-velocity` for? And how could we contribute to removing jQuery from the project?

Could you give us more details?

**Comment by jondot** [comment]
@DevManny `tweene-velocity` is used to tween multiple values at once and for the timeline abstraction (add steps to a timeline, replay it, reverse it, loop it and so on).

In actuality, I think it is possible to remove the jquery dependency from `tweene-velocity` itself. It just requires some boring refactoring and testing work.

See [this](https://github.com/SkidX/tweene/blob/master/src/tweene-velocity.js#L55) for example, which uses the jQuery plugin system (`$.fn`) to get access to a previously set up velocity as a plugin.

**Comment by jondot** [comment]
@DevManny @ValBerthe please see progress in #18
