### ISSUE TITLE
Cannot read property 'store' of undefined

### ISSUE THREAD

**Issue by ValBerthe** [jondot/react-flight#12]
Hey ! Now that I managed to properly import jQuery into the project, I've been trying to implement it. 

Everything works fine with the imported component `Rect`. But am I not supposed to be able to use my own components as well ?

Steps to reproduce : 

```
<Flight interactive ref={flight => (this.flight = flight)}>
  <Flight.Frame duration={300} source interactive>
    <div className="keyframe">
      <MyCustomComponent style={...} />
    </div>
  </Flight.Frame>
  <Flight.Frame duration={300}>
    <div className="keyframe">
      <MyCustomComponent style={...} />
    </div>
  </Flight.Frame>
</Flight>
```

Error:

```
connectAdvanced.js:113: Uncaught TypeError: Cannot read property 'store' of undefined
    at new Connect (http://localhost:3001/static/js/bundle.js:62754:49)
    at http://localhost:3001/static/js/bundle.js:266516:26
    at Array.map (native)
    at walk (http://localhost:3001/static/js/bundle.js:266500:52)
    at http://localhost:3001/static/js/bundle.js:266535:14
    at Array.map (native)
    at walk (http://localhost:3001/static/js/bundle.js:266500:52)
    at extract (http://localhost:3001/static/js/bundle.js:266541:105)
    at Array.map (native)
    at styles (http://localhost:3001/static/js/bundle.js:266544:60)
    at new Director (http://localhost:3001/static/js/bundle.js:266559:20)
    at http://localhost:3001/static/js/bundle.js:266718:26
```

Tried:

- To nest my component inside a `Rect`,
- To assign `name`, `id`, `className` to the component.

Am I doing something wrong here ? Has the `registerServiceWorker` anything to do with it ?

**Comment by jondot** [comment]
It sounds like store is part of a bigger redux or similar stack that you have?

**Comment by ValBerthe** [comment]
@jondot you're right. But the error is due to Flight (I guess `new Director` and `walk` is part of it).

**Comment by jondot** [comment]
What react-flight does part of `walk` is to try and render components, so that it can measure how it would layout in animation (the React component tree isn't deeply rendered at the time of evaluation).

This means [instantiating](https://github.com/jondot/react-flight/blob/master/src/core/director.js#L29) some of the components when needed. It may be that there is some kind of store setup that is done when trying to render in this way (that is out of the scope of react-flight).

What i'm wondering about is that you see that simple divs and rect aren't working. For sanity's sake - is the simple example working for you? (i.e. the vanilla `react-flight` example).

**Comment by ValBerthe** [comment]
OK, I found out what's wrong. It seems that `Flight.Frame` does not accept components connected to redux containers as children.

**Comment by jondot** [comment]
And I assume everything is wrapped with Provider in your case right? (including Flight and Flight.Frames)

**Comment by ValBerthe** [comment]
Yes, Provider is wrapping the <App/>.

**Comment by jondot** [comment]
Got it. Generally integrating into a stateful app was out of scope for react-flight but I'm going to scaffold a redux app (god knows that takes time with all the options and configs :) ).
Then I'll see if it's possible to support stateful or redux apps and what's really the gist of the problem.

**Comment by ValBerthe** [comment]
Allright ! It's not really game-breaking though, the most important thing for now is to be aware of it :)
For a longer term, it would be awesome to have redux apps supported. 👍

**Comment by jondot** [comment]
Took a couple of hours of drilling into React internals, and I finally came up with a solution that's not hacky, but hopefully supports enough use cases with Redux (the hacky solution involved extracting `_context` from React internals, and would have worked better, but I preferred not going there).

Releasing a new version and pushing code in a bit!

**Comment by jondot** [comment]
Version `1.0.2` is out with Redux support. Thanks for driving this effort!
You can get directly to the gist of how to make it work here:

https://github.com/jondot/react-flight/blob/master/examples/compos-redux/src/App.js

Note this is a new redux-centric sample. The trick now is to require your store context with the `Flight` component, and it'll carry this context forward during deep rendering.


```javascript
Flight.contextTypes = {
  store: PropTypes.object,
}

Flight.childContextTypes = {
  ...Flight.childContextTypes,
  store: PropTypes.object,
}
```

Hope this works for you!

**Comment by ValBerthe** [comment]
Awesome ! Thanks !

**Comment by jondot** [comment]
Tidying up. Please reopen if more questions pop up 👍
