### ISSUE TITLE
[question] Will it work with React Native ?

### ISSUE THREAD

**Issue by yash2code** [jondot/react-flight#13]

**Comment by jondot** [comment]
Great question! I really want that to happen, so currently the architecture supports it. The DOM specific stuff are tucked under `dom`.

There's some leg work to do for it to work for React Native, and that's part of the plan. Until that happens I'm accepting pull requests :)

**Comment by pedrolucasp** [comment]
@jondot And what would be that "leg work"? Or how can we engage with the project?

Nice work with this project, btw 👍

**Comment by jondot** [comment]
@pedrolucasp thanks!

Basically what's missing is some research on native animation driving this in React Native, and then building a composer. A composer is composing timelines of tweens for every frame. So on React Native, it would need to grab components by reference, compose these by frame and drive them (ideally by native driver).

Here's the default one, based on Velocity (for driving animation) and Tweene (for streamlining timelines across various DOM animation drivers).

https://github.com/jondot/react-flight/blob/master/src/core/velocity-composer.js

**Comment by jondot** [comment]
Tidying up. Please reopen if more questions on this topic pop up.
